app-lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
result:
  scale: 1
redis:
  scale: 1
vote:
  scale: 2
worker:
  scale: 1
postgres:
  scale: 1